name: Build Images
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'

jobs:
  ## linux / ubuntu
  ubuntu-24:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: ubuntu-24
      tags: ubuntu-noble ubuntu latest
      platforms: linux/amd64
  ubuntu-22:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: ubuntu-22
      tags: ubuntu-jammy
      platforms: linux/amd64
  ubuntu-20:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: ubuntu-20
      tags: ubuntu-focal
      platforms: linux/amd64
  ubuntu-18:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: ubuntu-18
      tags: ubuntu-bionic
      platforms: linux/amd64
  ubuntu-16:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: ubuntu-16
      tags: ubuntu-xenial
      platforms: linux/amd64

  ## linux / debian
  debian-12:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: debian-12
      tags: debian-bookworm debian
      platforms: linux/amd64,linux/arm/v7,linux/arm64
  debian-11:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: debian-11
      tags: debian-bullseye
      platforms: linux/amd64,linux/arm/v7,linux/arm64
  debian-10:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      name: debian-10
      tags: debian-buster
      platforms: linux/amd64,linux/arm/v7,linux/arm64

  ## linux / alpine
  alpine-3:
    uses: ./.github/workflows/_build-linux.yml
    needs: ubuntu-22
    secrets: inherit
    with:
      name: alpine-3
      tags: alpine
      platforms: linux/amd64

  ## linux / rocky
  rocky-9:
    uses: ./.github/workflows/_build-linux.yml
    needs: ubuntu-22
    secrets: inherit
    with:
      name: rocky-9
      tags: rocky
      platforms: linux/amd64
  rocky-8:
    uses: ./.github/workflows/_build-linux.yml
    needs: ubuntu-22
    secrets: inherit
    with:
      name: rocky-8
      platforms: linux/amd64

  ## linux / centos
  centos-9:
    uses: ./.github/workflows/_build-linux.yml
    needs: ubuntu-22
    secrets: inherit
    with:
      name: centos-9
      tags: centos
      platforms: linux/amd64
  centos-8:
    uses: ./.github/workflows/_build-linux.yml
    needs: ubuntu-22
    secrets: inherit
    with:
      name: centos-8
      platforms: linux/amd64

  ## windows / default
  windows-1809:
    uses: ./.github/workflows/_build-windows.yml
    secrets: inherit
    with:
      name: windows-1809
      tags: windows

  ## windows / core
  windows-core-2019:
    uses: ./.github/workflows/_build-windows.yml
    secrets: inherit
    with:
      name: windows-core-2019
      tags: windows-core
  windows-core-1809:
    uses: ./.github/workflows/_build-windows.yml
    secrets: inherit
    with:
      name: windows-core-1809
